name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Check Prettier formatting
      run: npm run format:check
      
    - name: Run TypeScript type check
      run: npm run type-check
      
    - name: Build library
      run: npm run build
      
    - name: Test build output
      run: |
        # Check if dist directory exists and contains expected files
        test -d dist
        test -f dist/index.js
        test -f dist/index.d.ts
        test -f dist/index.d.ts.map
        echo "✅ Build output verified"
        
    - name: Run complete CI check
      run: npm run ci:check
